#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

red=`tput setaf 1`
green=`tput setaf 2`
yellow=`tput setaf 3`
blue=`tput setaf 4`
magenta=`tput setaf 5`
cyan=`tput setaf 6`
bold=`tput bold`
reset=`tput sgr0`

#===================== PHP =====================

echo "👷🔍 Checking code convention\n"

# checking phpmd
./vendor/bin/phpmd app,config,routes text phpmd.xml ||
(
  echo "${red}[Check phpmd failed]${reset} Your php code SUCKS. 🤬🖕\n"
  false;
)
echo "${green}[✅ Check phpmd OK]${reset}\n"

# Check pint
./vendor/bin/pint --config pint.json --dirty --test ||
(
  echo "${red}[Check code style failed]${reset} Your php code styling looks disgusting. 🤢🤮"
  echo "👷🔨 Run ${cyan}${bold}npm run pint${reset} to fix it"
  echo "     Then add changes & commit again!\n"
  false;
)
echo "${green}[✅ Check code style OK]${reset}\n"

#===================== FE =====================

# Check Prettier standards
npm run check-format ||
(
  echo "${red}[Prettier Check Failed]${reset} Your code styling looks disgusting. 🤢🤮
    1. Run ${cyan}${bold}npm run format${reset} or ${cyan}${bold}yarn format${reset} to fix it,
    2. Add changes and try commit again."
  false;
)
echo "${green}[Prettier Check OK]${reset}"

# Check ESLint
npm run lint ||
(
  echo "${red}[ESLint Check Failed]${reset} Get that weak shit out of here! 😤❌
    Make the changes required above and try again."
  false; 
)
echo "${green}[ESLint Check OK]${reset}"

# # All check passed... Trying to build app
# echo "\nAlright.... Code looks good to me... Trying to build now. 🤔🤔"
# npm run build ||
# (
#   echo "${red}[FE build failed]${reset} Hey Loser! ❌🔨
#     View the errors above to see why."
#   false;
# )

# Now we can commit
echo "\n${green}[All Check SUCCESS]${reset} You're doing great, Babe. 👍🎉
  ${cyan}❤️ I am committing this now ❤️${reset}\n"
